# Generated by Django 5.1.5 on 2025-12-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
